AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  quadratic-equation

  Sample SAM Template for quadratic-equation

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  QuadraticEquationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: quadratic_equation/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        QuadraticEquation:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /quadratic-equation
            Method: get
            RequestParameters:
              - method.request.querystring.numbers:
                 Required: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  QuadraticEquationApi:
    Description: "API Gateway endpoint URL for Prod stage for quadratic equation function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/quadratic-equation/"
  QuadraticEquationFunction:
    Description: "quadratic equation Lambda Function ARN"
    Value: !GetAtt QuadraticEquationFunction.Arn
  QuadraticEquationFunctionIamRole:
    Description: "Implicit IAM Role created for quadratic equation function"
    Value: !GetAtt QuadraticEquationFunctionRole.Arn
