AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  currency-conversion

  Sample SAM Template for currency-conversion

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CurrencyConversionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: currency_conversion/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        CurrencyConversion:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /currency-conversion
            Method: get
            RequestParameters:
              - method.request.querystring.numbers:
                 Required: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CurrencyConversionApi:
    Description: "API Gateway endpoint URL for Prod stage for currency conversion function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/currency-conversion/"
  CurrencyConversionFunction:
    Description: "currency conversion Lambda Function ARN"
    Value: !GetAtt CurrencyConversionFunction.Arn
  CurrencyConversionFunctionIamRole:
    Description: "Implicit IAM Role created for currency conversion function"
    Value: !GetAtt CurrencyConversionFunctionRole.Arn
